### ISSUE TITLE
Map images from DCSmaps.com not working in https

### ISSUE THREAD

**Issue by juliancastroorozco** [DCS-Web-Editor/dcs-web-viewer-deploy#1]
Hover on layers and select DCSmaps.com.
Images from DCSmaps.com comes as http but chrome redirects to https and fails

**Comment by fyyyyy** [comment]
see the faq on discord

Q: The DCSmaps DCSM map layer isnt loading or shows grey tiles
A: It only works in the Caucasus area. For some browsers you may need to enable mixed content for the editor website, as dcsmaps tiles are served over http not https You can also enable mixed content (just for this website) in Chrome, this allows it to load images over http. This is necessary until DCSmaps can serve map tiles via https.
https://experienceleague.adobe.com/docs/target/using/experiences/vec/troubleshoot-composer/mixed-content.html?lang=en

**Comment by juliancastroorozco** [comment]
Sorry don't have discord, hope it gets resolved properly
